"""Target paths shared with the website (data/paths.json, generated by `npm run export:paths` in web/).

Coordinates are millimetres on the 120 × 60 mm trace area, origin top-left, +y down — the same frame as the
Live Session canvas (960 × 480 px at 8 px/mm). Use deviation_mm() to score a fingertip position against a path.
"""
from __future__ import annotations
import json
from pathlib import Path

import numpy as np

PATHS_FILE = Path(__file__).resolve().parent.parent / "data" / "paths.json"
_cache = None


def load_paths(file=PATHS_FILE):
    global _cache
    if _cache is None or file != PATHS_FILE:
        data = json.loads(Path(file).read_text())["paths"]
        out = {p["id"]: {**p, "points_mm": np.asarray(p["points_mm"], dtype=float)} for p in data}
        if file != PATHS_FILE:
            return out
        _cache = out
    return _cache


def paths_for_level(level):
    return [p for p in load_paths().values() if p["level"] == level]


def deviation_mm(xy_mm, path_id):
    """Distance from each (x, y) point (mm) to the nearest point on the path polyline. xy_mm: (n, 2) or (2,)."""
    pts = load_paths()[path_id]["points_mm"]
    q = np.atleast_2d(np.asarray(xy_mm, dtype=float))
    a, b = pts[:-1], pts[1:]
    ab = b - a
    ab2 = (ab**2).sum(axis=1) + 1e-12
    # project every query point onto every segment (clamped), take the minimum distance
    ap = q[:, None, :] - a[None, :, :]
    u = np.clip((ap * ab[None]).sum(axis=2) / ab2[None], 0, 1)
    closest = a[None] + u[..., None] * ab[None]
    return np.sqrt(((q[:, None, :] - closest) ** 2).sum(axis=2)).min(axis=1)


def accuracy_pct(dev_mm, tolerance_mm):
    """ACC = 100 · N(d ≤ τ) / N  (same definition as the site)."""
    d = np.asarray(dev_mm, dtype=float)
    return float(100 * (d <= tolerance_mm).mean()) if len(d) else 0.0
